[workspace]
members  = ["crates/*"]
resolver = "2"

    [workspace.package]
    authors = ["magic-akari <akari.ccino@gmail.com>"]
    description = "JavaScript/TypeScript formatter powered by wasm ported from Rome"
    edition = "2021"
    homepage = "https://github.com/wasm-fmt/rome_fmt"
    keywords = [
        "wasm",
        "JavaScript",
        "TypeScript",
        "JSX",
        "TSX",
        "formatter",
        "Rome",
    ]
    license = "MIT"
    readme = "README.md"
    repository = "https://github.com/wasm-fmt/rome_fmt"
    version = "0.0.2"


    [workspace.dependencies]
    biome_formatter    = "0.1.0"
    biome_js_formatter = "0.1.0"
    biome_js_parser    = "0.1.0"
    biome_js_syntax    = "0.1.0"
    serde              = { version = "1.0" }
    serde_json         = { version = "1.0" }
    wasm-bindgen       = "0.2.87"

[profile.release]
lto       = true
opt-level = "s"
